/**
 * This demo shows one possible way of implementing nodes as circular images
 */
function onLoad() {
  var graphics = Viva.Graph.View.svgGraphics();

  // we will use SVG patterns to fill circle with image brush:
  // http://stackoverflow.com/questions/11496734/add-a-background-image-png-to-a-svg-circle-shape
  var defs = Viva.Graph.svg('defs');
  graphics.getSvgRoot().append(defs);

  graphics.node(createNodeWithImage)
    .placeNode(placeNodeWithTransform);

  var graph = constructGraph();
  var renderer = Viva.Graph.View.renderer(graph, {
    graphics: graphics,
    container: document.getElementById('graph-container')
  });

  renderer.run();

  function createNodeWithImage(node) {
    var radius = 12;
    // First, we create a fill pattern and add it to SVG's defs:
    var pattern = Viva.Graph.svg('pattern')
      .attr('id', "imageFor_" + node.id)
      .attr('patternUnits', "userSpaceOnUse")
      .attr('width', 600)
      .attr('height', 600)
    var image = Viva.Graph.svg('image')
      .attr('x', '0')
      .attr('y', '0')
      .attr('height', radius * 2)
      .attr('width', radius * 2)
      .link(node.data.url);
    pattern.append(image);
    defs.append(pattern);

    // now create actual node and reference created fill pattern:
    var ui = Viva.Graph.svg('g');
    var circle = Viva.Graph.svg('circle')
      .attr('cx', radius)
      .attr('cy', radius)
      .attr('fill', 'url(#imageFor_' + node.id + ')')
      .attr('r', radius);

    ui.append(circle);
    return ui;
  }

  function placeNodeWithTransform(nodeUI, pos) {
    // Shift image to let links go to the center:
    nodeUI.attr('transform', 'translate(' + (pos.x - 12) + ',' + (pos.y - 12) + ')');
  }
}


function constructGraph() {
      var stuff = [
   
   {
    "kind": "track",
    "id": 1338778,
    "created_at": "2010/01/13 10:49:42 +0000",
    "user_id": 513508,
    "duration": 646269,
    "commentable": true,
    "state": "finished",
    "original_content_size": 20656230,
    "last_modified": "2014/12/04 15:29:40 +0000",
    "sharing": "public",
    "tag_list": "Pär Grindvik Do Us Part Drumcode",
    "permalink": "par-grindvik-do-us-part-drumcode",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "https://www.beatport.com/en-US/html/content/release/detail/37825/Swedish%20Silver",
    "label_id": null,
    "purchase_title": null,
    "genre": "Electronic, Techno",
    "title": "Par Grindvik - Do Us Part - Drumcode",
    "description": "",
    "label_name": "Drumcode",
    "release": "DC10YEARS",
    "track_type": "original",
    "key_signature": "",
    "isrc": "",
    "video_url": "http://www.youtube.com/watch?v=EYMbN0EL2zk",
    "bpm": null,
    "release_year": 2006,
    "release_month": 11,
    "release_day": 20,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/1338778",
    "user":  {
      "id": 513508,
      "kind": "user",
      "permalink": "grindvik",
      "username": "Pär Grindvik",
      "last_modified": "2014/11/05 10:41:21 +0000",
      "uri": "https://api.soundcloud.com/users/513508",
      "permalink_url": "http://soundcloud.com/grindvik",
      "avatar_url": "https://i1.sndcdn.com/avatars-000104601338-guhkqx-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/grindvik/par-grindvik-do-us-part-drumcode",
    "artwork_url": "https://i1.sndcdn.com/artworks-000000853541-2e0xac-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/He1i0ddRHURy_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/1338778/stream",
    "playback_count": 5810,
    "download_count": 2,
    "favoritings_count": 194,
    "comment_count": 30,
    "attachments_uri": "https://api.soundcloud.com/tracks/1338778/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 6987810,
    "created_at": "2010/11/13 19:20:14 +0000",
    "user_id": 1193134,
    "duration": 277133,
    "commentable": true,
    "state": "finished",
    "original_content_size": 6649587,
    "last_modified": "2015/02/08 15:50:31 +0000",
    "sharing": "public",
    "tag_list": "Jay-Z Prodigy 99 problems ",
    "permalink": "99-problems-the-prodigy-remix-dirty",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "Hiphop",
    "title": "Jay-Z - 99 Problems :: The Prodigy Remix",
    "description": "Was asked to remix one of all time favourite tunes, so here it is 99 problems Jay-Z - the prodigy remix\r\nPlay it loud!\r\nLH\r\n\r\nhttp://theprodigy.com/latest-news/37-homepage-section/422-99-prodigy\r\n\r\nSignup to the email newsletter here http://theprodigy.com/the-prodigy/join-mailing-list",
    "label_name": "",
    "release": "",
    "track_type": "remix",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/6987810",
    "user":  {
      "id": 1193134,
      "kind": "user",
      "permalink": "theprodigy",
      "username": "The Prodigy",
      "last_modified": "2015/02/24 15:31:21 +0000",
      "uri": "https://api.soundcloud.com/users/1193134",
      "permalink_url": "http://soundcloud.com/theprodigy",
      "avatar_url": "https://i1.sndcdn.com/avatars-000099241563-1cwmm9-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/theprodigy/99-problems-the-prodigy-remix-dirty",
    "artwork_url": "https://i1.sndcdn.com/artworks-000003502327-kxqjby-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/ScHYqWcvrFSM_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/6987810/stream",
    "playback_count": 1998793,
    "download_count": 32507,
    "favoritings_count": 24135,
    "comment_count": 856,
    "attachments_uri": "https://api.soundcloud.com/tracks/6987810/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 6953476,
    "created_at": "2010/11/12 16:56:15 +0000",
    "user_id": 200380,
    "duration": 352002,
    "commentable": true,
    "state": "finished",
    "original_content_size": 14072686,
    "last_modified": "2015/02/08 00:20:22 +0000",
    "sharing": "public",
    "tag_list": "drop the lime",
    "permalink": "drop-the-lime-hot-as-hell-canblaster-remix",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "Horsestep",
    "title": "Drop The Lime - Hot As Hell (Canblaster Remix)",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": "remix",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": 132,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/6953476",
    "user":  {
      "id": 200380,
      "kind": "user",
      "permalink": "canblaster",
      "username": "CANBLASTER (Club Cheval)",
      "last_modified": "2015/02/01 14:15:59 +0000",
      "uri": "https://api.soundcloud.com/users/200380",
      "permalink_url": "http://soundcloud.com/canblaster",
      "avatar_url": "https://i1.sndcdn.com/avatars-000054260126-ao7i2b-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/canblaster/drop-the-lime-hot-as-hell-canblaster-remix",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/J5hnQkWjqPSt_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/6953476/stream",
    "playback_count": 81387,
    "download_count": 821,
    "favoritings_count": 1604,
    "comment_count": 199,
    "attachments_uri": "https://api.soundcloud.com/tracks/6953476/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 3544719,
    "created_at": "2010/06/20 06:42:52 +0000",
    "user_id": 274768,
    "duration": 82160,
    "commentable": true,
    "state": "finished",
    "original_content_size": 3287166,
    "last_modified": "2012/11/04 16:07:16 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "pulse-excerpt-short-experiment",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Pulse/Excerpt/Short Experiment",
    "description": "unreleased, edits.\r\n\r\n",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/3544719",
    "user":  {
      "id": 274768,
      "kind": "user",
      "permalink": "richarddevine",
      "username": "RichardDevine",
      "last_modified": "2015/02/28 16:29:06 +0000",
      "uri": "https://api.soundcloud.com/users/274768",
      "permalink_url": "http://soundcloud.com/richarddevine",
      "avatar_url": "https://i1.sndcdn.com/avatars-000101598548-n3mtyb-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/richarddevine/pulse-excerpt-short-experiment",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001691438-lokx4h-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/ABfvfcdg11bl_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/3544719/stream",
    "playback_count": 4355,
    "download_count": 2,
    "favoritings_count": 55,
    "comment_count": 18,
    "attachments_uri": "https://api.soundcloud.com/tracks/3544719/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 5667089,
    "created_at": "2010/09/29 12:28:27 +0000",
    "user_id": 627054,
    "duration": 195103,
    "commentable": true,
    "state": "finished",
    "original_content_size": 34390988,
    "last_modified": "2015/02/28 09:57:08 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "brian-eno-2-forms-of-anger-small-craft-on-a-milk-sea",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "http://brian-eno.net",
    "label_id": 627054,
    "purchase_title": null,
    "genre": "",
    "title": "Brian Eno with Jon Hopkins & Leo Abrahams - 2 Forms Of Anger (taken from Small Craft On A Milk Sea)",
    "description": "Details at http://brian-eno.net",
    "label_name": "Warp Records",
    "release": "WARP207",
    "track_type": "original",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": 2010,
    "release_month": 11,
    "release_day": 1,
    "original_format": "wav",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/5667089",
    "user":  {
      "id": 627054,
      "kind": "user",
      "permalink": "warp-records",
      "username": "Warp Records",
      "last_modified": "2015/01/17 18:15:15 +0000",
      "uri": "https://api.soundcloud.com/users/627054",
      "permalink_url": "http://soundcloud.com/warp-records",
      "avatar_url": "https://i1.sndcdn.com/avatars-000025268800-mj0hb0-large.jpg"
    },
    "label":  {
      "id": 627054,
      "kind": "user",
      "permalink": "warp-records",
      "username": "Warp Records",
      "last_modified": "2015/01/17 18:15:15 +0000",
      "uri": "https://api.soundcloud.com/users/627054",
      "permalink_url": "http://soundcloud.com/warp-records",
      "avatar_url": "https://i1.sndcdn.com/avatars-000025268800-mj0hb0-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/warp-records/brian-eno-2-forms-of-anger-small-craft-on-a-milk-sea",
    "artwork_url": "https://i1.sndcdn.com/artworks-000002474423-8xyyvz-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/hHNdRnAoZnAK_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/5667089/stream",
    "playback_count": 232673,
    "download_count": 0,
    "favoritings_count": 1588,
    "comment_count": 223,
    "attachments_uri": "https://api.soundcloud.com/tracks/5667089/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 6037332,
    "created_at": "2010/10/13 06:12:14 +0000",
    "user_id": 1444039,
    "duration": 169493,
    "commentable": true,
    "state": "finished",
    "original_content_size": 6775118,
    "last_modified": "2012/12/27 11:59:49 +0000",
    "sharing": "public",
    "tag_list": "knxwledge wait",
    "permalink": "knxwledge-wait",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "Abstract Hip Hop",
    "title": "Knxwledge - Wait",
    "description": "",
    "label_name": "All City Records",
    "release": "",
    "track_type": "original",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/6037332",
    "user":  {
      "id": 1444039,
      "kind": "user",
      "permalink": "zonkkk",
      "username": "Zonk",
      "last_modified": "2010/08/03 16:13:42 +0000",
      "uri": "https://api.soundcloud.com/users/1444039",
      "permalink_url": "http://soundcloud.com/zonkkk",
      "avatar_url": "https://a1.sndcdn.com/images/default_avatar_large.png"
    },
    "permalink_url": "http://soundcloud.com/zonkkk/knxwledge-wait",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/3jGSWmiw547j_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/6037332/stream",
    "playback_count": 8835,
    "download_count": 0,
    "favoritings_count": 116,
    "comment_count": 12,
    "attachments_uri": "https://api.soundcloud.com/tracks/6037332/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 6099624,
    "created_at": "2010/10/15 11:11:48 +0000",
    "user_id": 1919152,
    "duration": 92456,
    "commentable": true,
    "state": "finished",
    "original_content_size": 2218112,
    "last_modified": "2013/12/30 20:12:26 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "happy-birthday",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Happy Birthday",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/6099624",
    "user":  {
      "id": 1919152,
      "kind": "user",
      "permalink": "beshi",
      "username": "beshi",
      "last_modified": "2010/10/15 07:32:08 +0000",
      "uri": "https://api.soundcloud.com/users/1919152",
      "permalink_url": "http://soundcloud.com/beshi",
      "avatar_url": "https://a1.sndcdn.com/images/default_avatar_large.png"
    },
    "permalink_url": "http://soundcloud.com/beshi/happy-birthday",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/cqRPPrnHB3jh_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/6099624/stream",
    "playback_count": 35674,
    "download_count": 0,
    "favoritings_count": 98,
    "comment_count": 8,
    "attachments_uri": "https://api.soundcloud.com/tracks/6099624/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 2452062,
    "created_at": "2010/04/15 17:42:22 +0000",
    "user_id": 3193,
    "duration": 478483,
    "commentable": true,
    "state": "finished",
    "original_content_size": 7651995,
    "last_modified": "2015/02/27 14:18:51 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "left-feat-fabian-reichelt",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "https://itunes.apple.com/album/left-right-ep-feat.-fabian/id366573243?uo=4&at=10lPB8",
    "label_id": 54952,
    "purchase_title": null,
    "genre": "House & Techno",
    "title": "Marek Hemmann - Left (feat. Fabian Reichelt)",
    "description": "Written & produced by Marek Hemmann. Lyrics & vocals by Fabian Reichelt.",
    "label_name": "Freude am Tanzen",
    "release": "047",
    "track_type": "original",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": 127,
    "release_year": 2010,
    "release_month": 4,
    "release_day": 26,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/2452062",
    "user":  {
      "id": 3193,
      "kind": "user",
      "permalink": "marekhemmann",
      "username": "marekhemmann",
      "last_modified": "2014/12/09 18:18:54 +0000",
      "uri": "https://api.soundcloud.com/users/3193",
      "permalink_url": "http://soundcloud.com/marekhemmann",
      "avatar_url": "https://i1.sndcdn.com/avatars-000116236467-8985x5-large.jpg"
    },
    "label":  {
      "id": 54952,
      "kind": "user",
      "permalink": "freudeamtanzen",
      "username": "Freude am Tanzen",
      "last_modified": "2015/02/26 09:36:24 +0000",
      "uri": "https://api.soundcloud.com/users/54952",
      "permalink_url": "http://soundcloud.com/freudeamtanzen",
      "avatar_url": "https://i1.sndcdn.com/avatars-000041575256-sj9r6u-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/marekhemmann/left-feat-fabian-reichelt",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001253749-7kjv0i-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/hN800oH2BvnL_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/2452062/stream",
    "playback_count": 350199,
    "download_count": 0,
    "favoritings_count": 7063,
    "comment_count": 305,
    "attachments_uri": "https://api.soundcloud.com/tracks/2452062/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 5685803,
    "created_at": "2010/09/30 01:21:41 +0000",
    "user_id": 23821,
    "duration": 275827,
    "commentable": true,
    "state": "finished",
    "original_content_size": 48626518,
    "last_modified": "2014/08/21 11:16:37 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "eros",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": true,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "italo pop re-edit",
    "title": "Eros Ramazzotti: Terra Promessa - BOTTIN EDIT",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": "remix",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": 98,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "wav",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/5685803",
    "user":  {
      "id": 23821,
      "kind": "user",
      "permalink": "bottin",
      "username": "BOTTIN",
      "last_modified": "2015/01/25 03:28:58 +0000",
      "uri": "https://api.soundcloud.com/users/23821",
      "permalink_url": "http://soundcloud.com/bottin",
      "avatar_url": "https://i1.sndcdn.com/avatars-000123561616-b0yqck-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/bottin/eros",
    "artwork_url": "https://i1.sndcdn.com/artworks-000002481149-pwwsvk-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/GmV7wea14WiM_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/5685803/stream",
    "download_url": "https://api.soundcloud.com/tracks/5685803/download",
    "playback_count": 80058,
    "download_count": 14246,
    "favoritings_count": 505,
    "comment_count": 71,
    "attachments_uri": "https://api.soundcloud.com/tracks/5685803/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 5710212,
    "created_at": "2010/09/30 22:50:23 +0000",
    "user_id": 329179,
    "duration": 509085,
    "commentable": true,
    "state": "finished",
    "original_content_size": 20336076,
    "last_modified": "2015/01/21 20:34:45 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "lord-of-the-isles-with-an-angel",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "http://www.juno.co.uk/ppps/products/427235-01.htm",
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Lord Of The Isles - With An Angel",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": 100,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/5710212",
    "user":  {
      "id": 329179,
      "kind": "user",
      "permalink": "lordoftheisles",
      "username": "Lord Of The Isles",
      "last_modified": "2015/02/28 23:36:40 +0000",
      "uri": "https://api.soundcloud.com/users/329179",
      "permalink_url": "http://soundcloud.com/lordoftheisles",
      "avatar_url": "https://i1.sndcdn.com/avatars-000006444266-m6nsyw-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/lordoftheisles/lord-of-the-isles-with-an-angel",
    "artwork_url": "https://i1.sndcdn.com/artworks-000002569682-6lno0u-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/FYi5QrotFZth_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/5710212/stream",
    "playback_count": 12005,
    "download_count": 2,
    "favoritings_count": 370,
    "comment_count": 176,
    "attachments_uri": "https://api.soundcloud.com/tracks/5710212/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 3466497,
    "created_at": "2010/06/15 16:15:25 +0000",
    "user_id": 13909,
    "duration": 325060,
    "commentable": true,
    "state": "finished",
    "original_content_size": 13642117,
    "last_modified": "2012/02/25 15:04:39 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "16-16-isolation",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Isolation",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": null,
    "key_signature": null,
    "isrc": null,
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/3466497",
    "user":  {
      "id": 13909,
      "kind": "user",
      "permalink": "gmm",
      "username": "GMM",
      "last_modified": "2014/11/13 15:02:10 +0000",
      "uri": "https://api.soundcloud.com/users/13909",
      "permalink_url": "http://soundcloud.com/gmm",
      "avatar_url": "https://i1.sndcdn.com/avatars-000088940528-pvoizw-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/gmm/16-16-isolation",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/AB63SObBm3IY_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/3466497/stream",
    "playback_count": 1886,
    "download_count": 0,
    "favoritings_count": 19,
    "comment_count": 0,
    "attachments_uri": "https://api.soundcloud.com/tracks/3466497/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 3208660,
    "created_at": "2010/05/31 20:12:39 +0000",
    "user_id": 307105,
    "duration": 326210,
    "commentable": true,
    "state": "finished",
    "original_content_size": 86262426,
    "last_modified": "2011/05/22 20:51:48 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "sun-is-out-zack-resnap",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Sun Is Out (Zack Resnap)",
    "description": "A Remix of Rumles ¨Sun Is Out¨ by Zack Christ\r\n\r\nhttp://soundcloud.com/zack-christ\r\n",
    "label_name": "",
    "release": "",
    "track_type": "remix",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "wav",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/3208660",
    "user":  {
      "id": 307105,
      "kind": "user",
      "permalink": "rumle",
      "username": "Rumle",
      "last_modified": "2014/09/17 15:41:21 +0000",
      "uri": "https://api.soundcloud.com/users/307105",
      "permalink_url": "http://soundcloud.com/rumle",
      "avatar_url": "https://i1.sndcdn.com/avatars-000066244959-y4v8oy-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/rumle/sun-is-out-zack-resnap",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001562036-l7jjpu-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/hcJsP74Q8kqR_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/3208660/stream",
    "playback_count": 1509,
    "download_count": 12,
    "favoritings_count": 48,
    "comment_count": 18,
    "attachments_uri": "https://api.soundcloud.com/tracks/3208660/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 4872909,
    "created_at": "2010/08/26 20:16:04 +0000",
    "user_id": 81070,
    "duration": 254059,
    "commentable": true,
    "state": "finished",
    "original_content_size": 10158571,
    "last_modified": "2015/02/05 23:38:21 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "flying-high-in-the-sunshine",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "https://www.beatport.com/en-US/html/content/release/detail/282550/Rorschach%20No.%2085",
    "label_id": null,
    "purchase_title": null,
    "genre": "Hip-Hop",
    "title": "Flying High in the Sunshine",
    "description": "SoulThump out soon on Trackdonalds",
    "label_name": "",
    "release": "",
    "track_type": "original",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/4872909",
    "user":  {
      "id": 81070,
      "kind": "user",
      "permalink": "sephirot",
      "username": "Sephirot",
      "last_modified": "2014/12/02 18:36:54 +0000",
      "uri": "https://api.soundcloud.com/users/81070",
      "permalink_url": "http://soundcloud.com/sephirot",
      "avatar_url": "https://i1.sndcdn.com/avatars-000107681956-gacqr6-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/sephirot/flying-high-in-the-sunshine",
    "artwork_url": "https://i1.sndcdn.com/artworks-000002188608-7okn41-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/nd8Re5vWm5pd_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/4872909/stream",
    "playback_count": 2986,
    "download_count": 0,
    "favoritings_count": 99,
    "comment_count": 51,
    "attachments_uri": "https://api.soundcloud.com/tracks/4872909/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 914913,
    "created_at": "2009/11/15 02:25:06 +0000",
    "user_id": 365801,
    "duration": 490710,
    "commentable": true,
    "state": "finished",
    "original_content_size": 9816195,
    "last_modified": "2013/11/20 01:13:41 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "teufelsberg",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "realistic resampler ",
    "title": "TEUFELSBERG",
    "description": "Teufelsberg: the old spying base built by the Allies during the Cold War, an abandoned monster with very intense vocal cord.\r\n\r\nThis is part of Flaneur Berlin, a live cinema piece that takes the city of Berlin as a character. For some video excerpts go to: www.vimeo.com/2351668\r\n\r\nFor more informations, visit audiobeamers.net",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/914913",
    "user":  {
      "id": 365801,
      "kind": "user",
      "permalink": "klinid",
      "username": "AudiobeamerS",
      "last_modified": "2014/12/04 10:13:22 +0000",
      "uri": "https://api.soundcloud.com/users/365801",
      "permalink_url": "http://soundcloud.com/klinid",
      "avatar_url": "https://i1.sndcdn.com/avatars-000000847447-bpwz4z-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/klinid/teufelsberg",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/0yuqle25hmI9_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/914913/stream",
    "playback_count": 197381,
    "download_count": 0,
    "favoritings_count": 303,
    "comment_count": 70,
    "attachments_uri": "https://api.soundcloud.com/tracks/914913/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 4194528,
    "created_at": "2010/07/25 17:23:06 +0000",
    "user_id": 217087,
    "duration": 196253,
    "commentable": true,
    "state": "finished",
    "original_content_size": 7847232,
    "last_modified": "2014/11/13 19:20:26 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "mount-kimbie-would-know",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "http://www.surus.co.uk/hotflush-recordings/crooks-and-lovers-10183.aspx",
    "label_id": null,
    "purchase_title": null,
    "genre": "Bass",
    "title": "Mount Kimbie - Would Know (from Crooks & Lovers)",
    "description": "from the debut album Crooks & Lovers, available now from all good shops worldwide!\r\n\r\nWatch the music video for this track here: http://www.youtube.com/watch?v=-Fnv1CpfMq8",
    "label_name": "Hotflush Recordings",
    "release": "HFCD004",
    "track_type": "original",
    "key_signature": "",
    "isrc": "",
    "video_url": "http://www.youtube.com/watch?v=-Fnv1CpfMq8",
    "bpm": null,
    "release_year": 2010,
    "release_month": 7,
    "release_day": 19,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/4194528",
    "user":  {
      "id": 217087,
      "kind": "user",
      "permalink": "hotflush",
      "username": "Hotflush",
      "last_modified": "2015/02/28 16:46:17 +0000",
      "uri": "https://api.soundcloud.com/users/217087",
      "permalink_url": "http://soundcloud.com/hotflush",
      "avatar_url": "https://i1.sndcdn.com/avatars-000106190303-0wxi66-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/hotflush/mount-kimbie-would-know",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001942579-9c10z2-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/Z2tVg2fFHIyD_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/4194528/stream",
    "playback_count": 22929,
    "download_count": 0,
    "favoritings_count": 345,
    "comment_count": 37,
    "attachments_uri": "https://api.soundcloud.com/tracks/4194528/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 2447522,
    "created_at": "2010/04/15 11:14:10 +0000",
    "user_id": 129172,
    "duration": 69302,
    "commentable": true,
    "state": "finished",
    "original_content_size": 2215184,
    "last_modified": "2014/03/22 14:15:43 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "track-4-jungle-jungle-jungle",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Track 4 - Jungle! Jungle! Jungle",
    "description": "",
    "label_name": null,
    "release": "",
    "track_type": null,
    "key_signature": null,
    "isrc": null,
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/2447522",
    "user":  {
      "id": 129172,
      "kind": "user",
      "permalink": "timexile",
      "username": "timexile",
      "last_modified": "2015/01/05 17:18:07 +0000",
      "uri": "https://api.soundcloud.com/users/129172",
      "permalink_url": "http://soundcloud.com/timexile",
      "avatar_url": "https://i1.sndcdn.com/avatars-000004881724-gsyj3i-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/timexile/track-4-jungle-jungle-jungle",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001252116-xieh8h-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/znuVPIabXsEX_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/2447522/stream",
    "playback_count": 1867,
    "download_count": 0,
    "favoritings_count": 13,
    "comment_count": 4,
    "attachments_uri": "https://api.soundcloud.com/tracks/2447522/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 3703259,
    "created_at": "2010/06/29 14:20:33 +0000",
    "user_id": 1187525,
    "duration": 365643,
    "commentable": true,
    "state": "finished",
    "original_content_size": 14618535,
    "last_modified": "2015/02/16 21:23:05 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "warhead-original-mix",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Warhead - Original Mix",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/3703259",
    "user":  {
      "id": 1187525,
      "kind": "user",
      "permalink": "rebel-instinct",
      "username": "Rebel Instinct",
      "last_modified": "2011/07/14 15:00:47 +0000",
      "uri": "https://api.soundcloud.com/users/1187525",
      "permalink_url": "http://soundcloud.com/rebel-instinct",
      "avatar_url": "https://i1.sndcdn.com/avatars-000001362639-n0mluz-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/rebel-instinct/warhead-original-mix",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/qA0JTRKwPABn_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/3703259/stream",
    "playback_count": 3305,
    "download_count": 498,
    "favoritings_count": 92,
    "comment_count": 24,
    "attachments_uri": "https://api.soundcloud.com/tracks/3703259/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 3585171,
    "created_at": "2010/06/22 14:15:51 +0000",
    "user_id": 572141,
    "duration": 251027,
    "commentable": true,
    "state": "finished",
    "original_content_size": 5019779,
    "last_modified": "2015/02/17 10:49:41 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "lets-get-lost",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Let's Get Lost",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/3585171",
    "user":  {
      "id": 572141,
      "kind": "user",
      "permalink": "batforlashes",
      "username": "Bat for Lashes",
      "last_modified": "2014/11/05 11:51:19 +0000",
      "uri": "https://api.soundcloud.com/users/572141",
      "permalink_url": "http://soundcloud.com/batforlashes",
      "avatar_url": "https://i1.sndcdn.com/avatars-000019149952-raiq09-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/batforlashes/lets-get-lost",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/Hwi2fgjTRZln_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/3585171/stream",
    "playback_count": 463272,
    "download_count": 0,
    "favoritings_count": 2837,
    "comment_count": 145,
    "attachments_uri": "https://api.soundcloud.com/tracks/3585171/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 3600352,
    "created_at": "2010/06/23 09:24:08 +0000",
    "user_id": 3193,
    "duration": 399459,
    "commentable": true,
    "state": "finished",
    "original_content_size": 6388087,
    "last_modified": "2015/02/27 14:18:51 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "manaus-madness-marek-hemmann-remix",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "https://itunes.apple.com/album/manaus-madness-marek-hemmann/id376152507?i=376152508&uo=4&at=10lPB8",
    "label_id": null,
    "purchase_title": "Buy on iTunes",
    "genre": "House & Techno",
    "title": "Manaus Madness (Marek Hemmann Remix)",
    "description": "",
    "label_name": "Voltage Musique Records",
    "release": "030",
    "track_type": "remix",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": 125,
    "release_year": 2010,
    "release_month": 6,
    "release_day": 25,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/3600352",
    "user":  {
      "id": 3193,
      "kind": "user",
      "permalink": "marekhemmann",
      "username": "marekhemmann",
      "last_modified": "2014/12/09 18:18:54 +0000",
      "uri": "https://api.soundcloud.com/users/3193",
      "permalink_url": "http://soundcloud.com/marekhemmann",
      "avatar_url": "https://i1.sndcdn.com/avatars-000116236467-8985x5-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/marekhemmann/manaus-madness-marek-hemmann-remix",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001711431-8rekdw-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/pWzmXaMtloE0_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/3600352/stream",
    "playback_count": 205755,
    "download_count": 0,
    "favoritings_count": 3572,
    "comment_count": 157,
    "attachments_uri": "https://api.soundcloud.com/tracks/3600352/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 2532898,
    "created_at": "2010/04/20 20:38:43 +0000",
    "user_id": 893511,
    "duration": 178405,
    "commentable": false,
    "state": "finished",
    "original_content_size": 31447222,
    "last_modified": "2012/04/17 21:19:15 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "as-we-enter-new-final-mix",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "As We Enter",
    "description": "",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "wav",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/2532898",
    "user":  {
      "id": 893511,
      "kind": "user",
      "permalink": "sparkart",
      "username": "Exclusive Music",
      "last_modified": "2014/05/13 23:27:26 +0000",
      "uri": "https://api.soundcloud.com/users/893511",
      "permalink_url": "http://soundcloud.com/sparkart",
      "avatar_url": "https://a1.sndcdn.com/images/default_avatar_large.png"
    },
    "permalink_url": "http://soundcloud.com/sparkart/as-we-enter-new-final-mix",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/pZHNsEJLETop_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/2532898/stream",
    "attachments_uri": "https://api.soundcloud.com/tracks/2532898/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 2215585,
    "created_at": "2010/03/30 18:03:32 +0000",
    "user_id": 537144,
    "duration": 315757,
    "commentable": true,
    "state": "finished",
    "original_content_size": 12718420,
    "last_modified": "2015/01/14 17:55:29 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "odessa",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Odessa",
    "description": "All songs written by Dan Snaith.\r\nLuke Lalonde sings 'Jamelia'.\r\nKyle Brenders plays soprano saxophone and bass clarinet on 'Kaili', 'Leave House', 'Hannibal'.\r\nColin Fisher plays tenor saxophone on 'Kaili', 'Leave House', 'Hannibal'.\r\nRob Piilonen plays flute on 'Kaili', 'Leave House', 'Hannibal', 'Jamelia'.\r\nSteve Ward plays trombone on 'Sun', 'Kaili', 'Leave House', 'Hannibal', ' Jamelia'.\r\n'Odessa', 'Kaili', 'Leave House', ' Lalibela', 'Jamelia' mixed by David Wrench at Bryn Derwen Studio.\r\n'Found Out' and 'Hannibal' mixed by Jeremy Greenspan at Pistacho Studio.\r\n'Bowls' mixed by Jeremy Greenspan and Dan Snaith.\r\nMastered by George Graves at Lacquer Channel Mastering.\r\nPhotography and art direction by Jason Evans. www.thedailynice.com\r\nDesign by Matthew Cooper and Jason Evans.",
    "label_name": "City Slang / Merge",
    "release": "",
    "track_type": null,
    "key_signature": null,
    "isrc": null,
    "video_url": null,
    "bpm": null,
    "release_year": 2010,
    "release_month": 4,
    "release_day": 19,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/2215585",
    "user":  {
      "id": 537144,
      "kind": "user",
      "permalink": "caribouband",
      "username": "Caribou.",
      "last_modified": "2015/01/26 20:10:27 +0000",
      "uri": "https://api.soundcloud.com/users/537144",
      "permalink_url": "http://soundcloud.com/caribouband",
      "avatar_url": "https://i1.sndcdn.com/avatars-000087522865-d205mo-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/caribouband/odessa",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001169676-rmu6ar-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/SxCUCesBzOlH_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/2215585/stream",
    "playback_count": 357756,
    "download_count": 0,
    "favoritings_count": 6563,
    "comment_count": 150,
    "attachments_uri": "https://api.soundcloud.com/tracks/2215585/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 2461489,
    "created_at": "2010/04/16 08:28:52 +0000",
    "user_id": 8,
    "duration": 56968,
    "commentable": true,
    "state": "finished",
    "original_content_size": 926628,
    "last_modified": "2015/02/13 17:38:50 +0000",
    "sharing": "public",
    "tag_list": "Eyjafjallajokull #the-icelandic-volcano-no-flight-blues #ashtag",
    "permalink": "the-icelandic-volcano-no-flight-at-all-blues",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "http://twitter.com/alexanderljung/status/12217650918",
    "label_id": null,
    "purchase_title": null,
    "genre": "Blues",
    "title": "The Icelandic Volcano No Flight (at all) Blues #ashtag",
    "description": "Woke up this morning…\r\n\r\nThe audio version of:\r\nhttp://twitter.com/alexanderljung/status/12217650918\r\n\r\nper request by:\r\nhttp://twitter.com/sitar/status/12224962819",
    "label_name": "",
    "release": "",
    "track_type": "original",
    "key_signature": "",
    "isrc": "",
    "video_url": "http://twitter.com/sitar/status/12224962819",
    "bpm": 88,
    "release_year": 2010,
    "release_month": 4,
    "release_day": 15,
    "original_format": "m4a",
    "license": "no-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/2461489",
    "user":  {
      "id": 8,
      "kind": "user",
      "permalink": "alex",
      "username": "Alex",
      "last_modified": "2015/02/23 04:38:56 +0000",
      "uri": "https://api.soundcloud.com/users/8",
      "permalink_url": "http://soundcloud.com/alex",
      "avatar_url": "https://i1.sndcdn.com/avatars-000064380920-cu9tg2-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/alex/the-icelandic-volcano-no-flight-at-all-blues",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001257054-bwec1w-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/IrJ6JLx4F2bR_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/2461489/stream",
    "playback_count": 4461,
    "download_count": 0,
    "favoritings_count": 54,
    "comment_count": 39,
    "attachments_uri": "https://api.soundcloud.com/tracks/2461489/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 1854947,
    "created_at": "2010/03/03 06:59:46 +0000",
    "user_id": 414405,
    "duration": 266445,
    "commentable": true,
    "state": "finished",
    "original_content_size": 8523481,
    "last_modified": "2013/07/19 03:44:42 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "quantec-electromagnetic-pulse",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": 414405,
    "purchase_title": null,
    "genre": "",
    "title": "",
    "description": "Track taken from the new album Deadbeat",
    "label_name": null,
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/1854947",
    "user":  {
      "id": 414405,
      "kind": "user",
      "permalink": "the-agriculture",
      "username": "the Agriculture Records",
      "last_modified": "2013/04/11 20:33:36 +0000",
      "uri": "https://api.soundcloud.com/users/414405",
      "permalink_url": "http://soundcloud.com/the-agriculture",
      "avatar_url": "https://i1.sndcdn.com/avatars-000036646501-tst8k3-large.jpg"
    },
    "label":  {
      "id": 414405,
      "kind": "user",
      "permalink": "the-agriculture",
      "username": "the Agriculture Records",
      "last_modified": "2013/04/11 20:33:36 +0000",
      "uri": "https://api.soundcloud.com/users/414405",
      "permalink_url": "http://soundcloud.com/the-agriculture",
      "avatar_url": "https://i1.sndcdn.com/avatars-000036646501-tst8k3-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/the-agriculture/quantec-electromagnetic-pulse",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001045711-bkd8c2-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/9n53jpohkVfY_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/1854947/stream",
    "playback_count": 2182,
    "download_count": 0,
    "favoritings_count": 21,
    "comment_count": 3,
    "attachments_uri": "https://api.soundcloud.com/tracks/1854947/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 1854892,
    "created_at": "2010/03/03 06:48:08 +0000",
    "user_id": 414405,
    "duration": 136358,
    "commentable": true,
    "state": "finished",
    "original_content_size": 4362279,
    "last_modified": "2012/04/14 18:45:45 +0000",
    "sharing": "public",
    "tag_list": "dub techno deadbeat deep dubstep",
    "permalink": "deadbeat-port-of-rix",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": 414405,
    "purchase_title": null,
    "genre": "",
    "title": "Deadbeat",
    "description": "",
    "label_name": null,
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/1854892",
    "user":  {
      "id": 414405,
      "kind": "user",
      "permalink": "the-agriculture",
      "username": "the Agriculture Records",
      "last_modified": "2013/04/11 20:33:36 +0000",
      "uri": "https://api.soundcloud.com/users/414405",
      "permalink_url": "http://soundcloud.com/the-agriculture",
      "avatar_url": "https://i1.sndcdn.com/avatars-000036646501-tst8k3-large.jpg"
    },
    "label":  {
      "id": 414405,
      "kind": "user",
      "permalink": "the-agriculture",
      "username": "the Agriculture Records",
      "last_modified": "2013/04/11 20:33:36 +0000",
      "uri": "https://api.soundcloud.com/users/414405",
      "permalink_url": "http://soundcloud.com/the-agriculture",
      "avatar_url": "https://i1.sndcdn.com/avatars-000036646501-tst8k3-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/the-agriculture/deadbeat-port-of-rix",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001045690-3b5cue-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/bOUEN02Z3H2L_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/1854892/stream",
    "playback_count": 1784,
    "download_count": 0,
    "favoritings_count": 19,
    "comment_count": 3,
    "attachments_uri": "https://api.soundcloud.com/tracks/1854892/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 1627313,
    "created_at": "2010/02/10 12:29:16 +0000",
    "user_id": 511721,
    "duration": 234355,
    "commentable": true,
    "state": "finished",
    "original_content_size": 5623257,
    "last_modified": "2013/10/25 13:52:03 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "06-autumn-music-1",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Autumn music 1",
    "description": "A selection from the album",
    "label_name": null,
    "release": "",
    "track_type": null,
    "key_signature": null,
    "isrc": null,
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/1627313",
    "user":  {
      "id": 511721,
      "kind": "user",
      "permalink": "max-richter",
      "username": "max richter",
      "last_modified": "2015/01/10 17:10:08 +0000",
      "uri": "https://api.soundcloud.com/users/511721",
      "permalink_url": "http://soundcloud.com/max-richter",
      "avatar_url": "https://i1.sndcdn.com/avatars-000088948643-8cbey8-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/max-richter/06-autumn-music-1",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/3jRGOXsVKTnd_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/1627313/stream",
    "playback_count": 435378,
    "download_count": 0,
    "favoritings_count": 398,
    "comment_count": 24,
    "attachments_uri": "https://api.soundcloud.com/tracks/1627313/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 2116375,
    "created_at": "2010/03/23 15:41:18 +0000",
    "user_id": 217087,
    "duration": 173179,
    "commentable": true,
    "state": "finished",
    "original_content_size": 2773076,
    "last_modified": "2014/09/11 14:59:35 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "mount-kimbie-remixes-pt-1-hfrmx006-preview",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "http://www.surus.co.uk/hotflush-recordings/mount-kimbie-remixes-10191.aspx",
    "label_id": 217087,
    "purchase_title": null,
    "genre": "Bass/Experimental",
    "title": "Mount Kimbie Remixes Pt. 1 (HFRMX006 Preview)",
    "description": "Mount Kimbie – Remixes Pt. 1\r\nCat number: HFRMX006\r\nRelease date: 19 April 2010\r\nA1: Maybes (James Blake Remix)\r\nA2: Serged (FaltyDL Remix)\r\nB1: At Least (Instra:mental Remix)",
    "label_name": "",
    "release": "HFRMX006",
    "track_type": "remix",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": 2010,
    "release_month": 4,
    "release_day": 19,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/2116375",
    "user":  {
      "id": 217087,
      "kind": "user",
      "permalink": "hotflush",
      "username": "Hotflush",
      "last_modified": "2015/02/28 16:46:17 +0000",
      "uri": "https://api.soundcloud.com/users/217087",
      "permalink_url": "http://soundcloud.com/hotflush",
      "avatar_url": "https://i1.sndcdn.com/avatars-000106190303-0wxi66-large.jpg"
    },
    "label":  {
      "id": 217087,
      "kind": "user",
      "permalink": "hotflush",
      "username": "Hotflush",
      "last_modified": "2015/02/28 16:46:17 +0000",
      "uri": "https://api.soundcloud.com/users/217087",
      "permalink_url": "http://soundcloud.com/hotflush",
      "avatar_url": "https://i1.sndcdn.com/avatars-000106190303-0wxi66-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/hotflush/mount-kimbie-remixes-pt-1-hfrmx006-preview",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001343916-4dedme-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/oEljqXlI22PO_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/2116375/stream",
    "playback_count": 11676,
    "download_count": 0,
    "favoritings_count": 158,
    "comment_count": 48,
    "attachments_uri": "https://api.soundcloud.com/tracks/2116375/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 444,
    "created_at": "2007/10/04 18:34:29 +0000",
    "user_id": 137,
    "duration": 259213,
    "commentable": true,
    "state": "finished",
    "original_content_size": 10369071,
    "last_modified": "2011/01/20 06:54:41 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "forss-paradigm-shift-rupert-remix",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": null,
    "title": "Forss: Paradigm Shift (Rupert Remix)",
    "description": "not that new really but this feels like a good place to put it …",
    "label_name": null,
    "release": null,
    "track_type": null,
    "key_signature": null,
    "isrc": null,
    "video_url": null,
    "bpm": 23.4,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/444",
    "user":  {
      "id": 137,
      "kind": "user",
      "permalink": "rupert-falsch",
      "username": "Rupert Falsch",
      "last_modified": "2015/02/27 10:49:24 +0000",
      "uri": "https://api.soundcloud.com/users/137",
      "permalink_url": "http://soundcloud.com/rupert-falsch",
      "avatar_url": "https://i1.sndcdn.com/avatars-000000354774-73aa9d-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/rupert-falsch/forss-paradigm-shift-rupert-remix",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/SpThVrxmYdID_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/444/stream",
    "playback_count": 1098,
    "download_count": 100,
    "favoritings_count": 20,
    "comment_count": 5,
    "attachments_uri": "https://api.soundcloud.com/tracks/444/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 1843921,
    "created_at": "2010/03/02 11:37:19 +0000",
    "user_id": 33226,
    "duration": 156428,
    "commentable": true,
    "state": "finished",
    "original_content_size": 6253713,
    "last_modified": "2014/11/27 18:34:40 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "hybris-the-cleaner",
    "streamable": false,
    "embeddable_by": "none",
    "downloadable": false,
    "purchase_url": null,
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Hybris - The Cleaner",
    "description": "Forthcoming on Critical - the debut release from Hybris. Serious sounds. ",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/1843921",
    "user":  {
      "id": 33226,
      "kind": "user",
      "permalink": "critical-music",
      "username": "Critical Music",
      "last_modified": "2015/02/23 11:48:23 +0000",
      "uri": "https://api.soundcloud.com/users/33226",
      "permalink_url": "http://soundcloud.com/critical-music",
      "avatar_url": "https://i1.sndcdn.com/avatars-000000828503-4gqus5-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/critical-music/hybris-the-cleaner",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001041992-zg56sw-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/01AF6aE9a2tg_m.png",
    "playback_count": 8821,
    "download_count": 0,
    "favoritings_count": 296,
    "comment_count": 65,
    "attachments_uri": "https://api.soundcloud.com/tracks/1843921/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 1535789,
    "created_at": "2010/02/01 19:46:22 +0000",
    "user_id": 5169,
    "duration": 314686,
    "commentable": true,
    "state": "finished",
    "original_content_size": 12582703,
    "last_modified": "2014/09/11 14:17:20 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "the-game-is-mine-ft-jtodd",
    "streamable": true,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "http://www.junodownload.com/ppps/products/1348578-02.htm",
    "label_id": null,
    "purchase_title": null,
    "genre": "HIP-MO-FUNK-BAD-ASS",
    "title": "THE GAME IS MINE FT. JTODD",
    "description": "Heavy & Dirty analogue synth bizz with some digi-tweaks.\r\nTrack from last year for project with j-todd on vox. Released on 4lux 2009. \r\n\r\nBuy it on Juno... pls follow link.\r\n\r\nThanks for support!\r\n",
    "label_name": "",
    "release": "",
    "track_type": "",
    "key_signature": "",
    "isrc": "",
    "video_url": null,
    "bpm": null,
    "release_year": null,
    "release_month": null,
    "release_day": null,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/1535789",
    "user":  {
      "id": 5169,
      "kind": "user",
      "permalink": "gerd",
      "username": "gerd",
      "last_modified": "2015/02/27 14:46:39 +0000",
      "uri": "https://api.soundcloud.com/users/5169",
      "permalink_url": "http://soundcloud.com/gerd",
      "avatar_url": "https://i1.sndcdn.com/avatars-000129916153-hd5kll-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/gerd/the-game-is-mine-ft-jtodd",
    "artwork_url": null,
    "waveform_url": "https://w1.sndcdn.com/tg4HS7DSu4Xb_m.png",
    "stream_url": "https://api.soundcloud.com/tracks/1535789/stream",
    "playback_count": 3281,
    "download_count": 0,
    "favoritings_count": 55,
    "comment_count": 43,
    "attachments_uri": "https://api.soundcloud.com/tracks/1535789/attachments",
    "policy": "ALLOW"
  },
   {
    "kind": "track",
    "id": 1848537,
    "created_at": "2010/03/02 19:15:23 +0000",
    "user_id": 421865,
    "duration": 248858,
    "commentable": true,
    "state": "finished",
    "original_content_size": 9949827,
    "last_modified": "2015/01/19 10:52:44 +0000",
    "sharing": "public",
    "tag_list": "",
    "permalink": "forest-families",
    "streamable": false,
    "embeddable_by": "all",
    "downloadable": false,
    "purchase_url": "http://theknife.net",
    "label_id": null,
    "purchase_title": null,
    "genre": "",
    "title": "Forest Families",
    "description": "",
    "label_name": null,
    "release": "RABID030",
    "track_type": null,
    "key_signature": null,
    "isrc": null,
    "video_url": null,
    "bpm": null,
    "release_year": 2006,
    "release_month": 1,
    "release_day": 1,
    "original_format": "mp3",
    "license": "all-rights-reserved",
    "uri": "https://api.soundcloud.com/tracks/1848537",
    "user":  {
      "id": 421865,
      "kind": "user",
      "permalink": "theknife",
      "username": "Rabid Records",
      "last_modified": "2014/08/04 08:54:48 +0000",
      "uri": "https://api.soundcloud.com/users/421865",
      "permalink_url": "http://soundcloud.com/theknife",
      "avatar_url": "https://i1.sndcdn.com/avatars-000000894858-n1vgax-large.jpg"
    },
    "permalink_url": "http://soundcloud.com/theknife/forest-families",
    "artwork_url": "https://i1.sndcdn.com/artworks-000001043512-of0rl8-large.jpg",
    "waveform_url": "https://w1.sndcdn.com/1HgJ3uGpLzkr_m.png",
    "playback_count": 25808,
    "download_count": 0,
    "favoritings_count": 177,
    "comment_count": 14,
    "attachments_uri": "https://api.soundcloud.com/tracks/1848537/attachments",
    "policy": "ALLOW"
  }
]
var graph = Viva.Graph.graph(); 
var titles = []; 
var imageurls = []; 
for(var i = 0; i < stuff.length; i++){
    titles[i] = stuff[i].title; 
    imageurls[i] = stuff[i].artwork_url; 
}


graph.addNode('user', {url : 'http://www.localcrimenews.com/wp-content/uploads/2013/07/default-user-icon-profile.png'}); 

for(var i = 0;i < titles.length; i++){
    
    graph.addNode(i, {url : imageurls[i]});
    graph.addLink('user', i);
    
}
  return graph;
}
